[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'skanehira/jumpcursor.vim'
hook_add = '''
  nmap <silent> ;j <Plug>(jumpcursor-jump)
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
augroup SetColorScheme 
	au!
	au VimEnter * nested colorscheme molokai
augroup END
	'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# Prettier
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = """
let g:ale_fixers = {
\   'typescript': ['prettier'],
\   'typescriptreact': ['prettier'],
\   'javascript': ['prettier'],
\   'javascriptreact': ['prettier'],
\   'css': ['prettier'],
\}

let g:ale_sign_error = 'P>'
let g:ale_sign_warning = 'P-'
let g:ale_echo_msg_format = '[%linter%] %code: %%s'
let g:ale_statusline_format = ['E%d', 'W%d', 'OK']

nmap <silent> <C-w>j <Plug>(ale_next_wrap)
nmap <silent> <C-w>k <Plug>(ale_previous_wrap)

let g:ale_fix_on_save = 1
let g:ale_javascript_prettier_use_local_config = 1
let g:ale_javascript_prettier_options = '--single-quote --trailing-comma all'
"""

# Git blame
[[plugins]]
repo = 'f-person/git-blame.nvim'

# Code Snippets
[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

# Git commands
[[plugins]]
repo = 'tpope/vim-fugitive'
