[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'skanehira/jumpcursor.vim'
hook_add = '''
  nmap <silent> ;j <Plug>(jumpcursor-jump)
'''

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
augroup SetColorScheme 
	au!
	au VimEnter * nested colorscheme molokai
augroup END
	'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
