[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    colorscheme tender
    set background=dark
    syntax on
    set t_Co=256
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
'''
